name: Build

on:
  workflow_call:

jobs:
  build-debug:
    name: Build debug binary
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Rust Environment
        uses: ./.github/actions/setup

      - name: Build debug binary
        run: cargo build

  build-release:
    name: Build release binary
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            artifact: jlo-darwin-x86_64
          - target: aarch64-apple-darwin
            artifact: jlo-darwin-aarch64
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Rust Environment
        uses: ./.github/actions/setup
        with:
          rust-version: 1.90.0

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          cp "${CARGO_TARGET_DIR:-target}/${{ matrix.target }}/release/jlo" ${{ matrix.artifact }}
          chmod +x ${{ matrix.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}
