name: Build

on:
  workflow_call:

jobs:
  build-debug:
    name: Build debug binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup

      - name: Build debug binary
        run: cargo build

  build-release:
    name: Build release binary
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: jlo-linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: jlo-linux-aarch64
            cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: jlo-darwin-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: jlo-darwin-aarch64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross (for cross-compilation)
        if: matrix.cross
        run: cargo install cross --version 0.2.5 --locked

      - name: Build release binary (native)
        if: ${{ !matrix.cross }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build release binary (cross)
        if: ${{ matrix.cross }}
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          cp target/${{ matrix.target }}/release/jlo ${{ matrix.artifact }}
          chmod +x ${{ matrix.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}
