name: Build

on:
  workflow_call:

jobs:
  build-debug:
    name: Build debug binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup

      - name: Build debug binary
        run: cargo build

  build-release:
    name: Build release binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary
        run: |
          cp target/release/jlo jlo-linux-x86_64
          chmod +x jlo-linux-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jlo-linux-x86_64
          path: jlo-linux-x86_64
